name: create tweet

on:
  schedule:
    - cron: '30 3 * * *' # Every dat at 9am
    - cron: '30 3-19 * * *' # Every 30 minutes past hour between 9am to 1am(+1)
    - cron: '45 3-19 * * *' # Every 45 minutes past hour between 9am to 1am(+1)

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run onthisday.py
        if: contains(github.event.schedule, '30 3 * * *')
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          NINJA_API_KEY: ${{ secrets.NINJA_API_KEY }}
        run: python onthisday.py    
          
      - name: execute py script # run numbers.py
        if: contains(github.event.schedule, '30 3-19 * * *')
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY}}
        run: python numbers.py

      - name: execute py script # run cats.py
        if: contains(github.event.schedule, '45 3-19 * * *')
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python cats.py
          
      - name: commit files
        run: |
          git config --local user.email "bora.jinam@gmail.com"
          git config --local user.name "jb1812"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
