name: run main.py

on:
  schedule:
    - cron: '30 5-15 * * *' # Every 30 minutes past hour between 11am to 8pm
    - cron: '45 5-15 * * *' # Every 45 minutes past hour between 11am to 8pm

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run A.py
        if: contains(github.event.schedule, '30 5-15 * * *')
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python A.py

      - name: execute py script # run B.py
        if: contains(github.event.schedule, '45 5-15 * * *')
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python B.py
          
      - name: commit files
        run: |
          git config --local user.email "bora.jinam@gmail.com"
          git config --local user.name "jb1812"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
